const INDIA_STATES = [
  { code: 'IN-MH', name: 'Maharashtra', economicProfile: 'Largest state economy; IT, finance, manufacturing, textiles, pharma hub. Mumbai is financial capital.', majorCities: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad'], tier2Cities: ['Kolhapur', 'Solapur', 'Amravati', 'Nanded'], dic: 'District Industries Centre (DIC)', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-DL', name: 'Delhi', economicProfile: 'National capital; trade, IT services, retail, hospitality, education, government services dominant.', majorCities: ['New Delhi', 'Delhi'], tier2Cities: [], dic: 'Delhi DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-KA', name: 'Karnataka', economicProfile: 'IT capital of India (Bengaluru); aerospace, biotech, silk, coffee, machine tools.', majorCities: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi'], tier2Cities: ['Belagavi', 'Davanagere', 'Ballari', 'Vijayapura'], dic: 'Karnataka DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-TN', name: 'Tamil Nadu', economicProfile: 'Auto manufacturing, IT, textiles, leather, petrochemicals. Chennai is auto hub.', majorCities: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'], tier2Cities: ['Salem', 'Tirunelveli', 'Vellore', 'Erode'], dic: 'Tamil Nadu DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-GJ', name: 'Gujarat', economicProfile: 'Diamond, petrochemicals, pharma, textiles, chemicals. Strong entrepreneurial culture. GIFT City emerging fintech hub.', majorCities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'], tier2Cities: ['Bhavnagar', 'Jamnagar', 'Junagadh', 'Gandhinagar'], dic: 'Gujarat DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-RJ', name: 'Rajasthan', economicProfile: 'Tourism, handicrafts, gems & jewellery, mining, textiles. Jaipur is pink city and startup hub.', majorCities: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota'], tier2Cities: ['Ajmer', 'Bikaner', 'Alwar', 'Bharatpur'], dic: 'Rajasthan DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-UP', name: 'Uttar Pradesh', economicProfile: 'Agriculture, IT (Noida/Greater Noida), leather, handicrafts, sugar. Largest state by population.', majorCities: ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Noida'], tier2Cities: ['Allahabad', 'Meerut', 'Bareilly', 'Aligarh'], dic: 'UP DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-WB', name: 'West Bengal', economicProfile: 'Jute, steel, engineering, IT, leather. Kolkata is trade and logistics hub for Eastern India.', majorCities: ['Kolkata', 'Howrah', 'Durgapur', 'Asansol'], tier2Cities: ['Siliguri', 'Malda', 'Bardhaman', 'Kalyani'], dic: 'West Bengal DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-TS', name: 'Telangana', economicProfile: 'IT/ITeS, pharma, biotech. Hyderabad is major IT and pharma hub (Genome Valley).', majorCities: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar'], tier2Cities: ['Khammam', 'Ramagundam', 'Mahbubnagar'], dic: 'Telangana DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-AP', name: 'Andhra Pradesh', economicProfile: 'Agriculture, aquaculture, mining, tourism. Amaravati is emerging capital. Vizag is industrial port city.', majorCities: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati'], tier2Cities: ['Kurnool', 'Rajahmundry', 'Nellore', 'Kakinada'], dic: 'AP DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-KL', name: 'Kerala', economicProfile: 'Tourism, fisheries, spices, IT, remittances. High human development. Kochi emerging fintech/startup hub.', majorCities: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur'], tier2Cities: ['Kollam', 'Palakkad', 'Alappuzha', 'Kannur'], dic: 'Kerala DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-MP', name: 'Madhya Pradesh', economicProfile: 'Agriculture, mining, tourism, manufacturing. Indore is commercial hub and cleanest city of India.', majorCities: ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur'], tier2Cities: ['Ujjain', 'Sagar', 'Dewas', 'Satna'], dic: 'MP DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-PB', name: 'Punjab', economicProfile: 'Agriculture (wheat/rice belt), small industries, sports goods (Jalandhar), hosiery (Ludhiana).', majorCities: ['Chandigarh', 'Ludhiana', 'Amritsar', 'Jalandhar'], tier2Cities: ['Patiala', 'Bathinda', 'Mohali', 'Hoshiarpur'], dic: 'Punjab DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-HR', name: 'Haryana', economicProfile: 'Auto, IT (Gurugram), agriculture, textiles. NCR belt is major startup and corporate hub.', majorCities: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala'], tier2Cities: ['Hisar', 'Rohtak', 'Sonipat', 'Karnal'], dic: 'Haryana DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-BR', name: 'Bihar', economicProfile: 'Agriculture, food processing, tourism (Buddhist circuit). Patna emerging as startup destination.', majorCities: ['Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur'], tier2Cities: ['Darbhanga', 'Purnia', 'Ara', 'Begusarai'], dic: 'Bihar DIC', gstThresholdNote: 'GST registration required above ₹20L turnover (₹10L for NE/special category)' },
  { code: 'IN-OR', name: 'Odisha', economicProfile: 'Steel, mining, tourism, agriculture. Bhubaneswar is emerging IT hub.', majorCities: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur'], tier2Cities: ['Sambalpur', 'Brahmapur', 'Baripada'], dic: 'Odisha DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-JH', name: 'Jharkhand', economicProfile: 'Mining, steel, cement. Ranchi emerging as service sector hub.', majorCities: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro'], tier2Cities: ['Deoghar', 'Hazaribagh', 'Giridih'], dic: 'Jharkhand DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-AS', name: 'Assam', economicProfile: 'Tea, petroleum, tourism, agriculture. Guwahati is Northeast India gateway.', majorCities: ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat'], tier2Cities: ['Tezpur', 'Tinsukia', 'Nagaon'], dic: 'Assam DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-CG', name: 'Chhattisgarh', economicProfile: 'Steel, mining, power, agriculture. Raipur is steel city.', majorCities: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba'], tier2Cities: ['Durg', 'Rajnandgaon', 'Jagdalpur'], dic: 'Chhattisgarh DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-UK', name: 'Uttarakhand', economicProfile: 'Tourism, pharmaceuticals, IT (Dehradun), hydropower. Industrial corridors in Haridwar/Roorkee.', majorCities: ['Dehradun', 'Haridwar', 'Roorkee', 'Haldwani'], tier2Cities: ['Rishikesh', 'Kashipur', 'Rudrapur'], dic: 'Uttarakhand DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-HP', name: 'Himachal Pradesh', economicProfile: 'Tourism, apple orchards, hydropower, pharmaceuticals. Shimla and Manali are major tourism hubs.', majorCities: ['Shimla', 'Manali', 'Dharamshala', 'Solan'], tier2Cities: ['Kullu', 'Mandi', 'Una', 'Hamirpur'], dic: 'HP DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-GA', name: 'Goa', economicProfile: 'Tourism, mining, IT, cashew processing. Smallest state with highest per-capita income.', majorCities: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa'], tier2Cities: ['Ponda', 'Bicholim'], dic: 'Goa DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-MN', name: 'Manipur', economicProfile: 'Agriculture, handicrafts, tourism. Imphal is border trade hub with Myanmar.', majorCities: ['Imphal'], tier2Cities: ['Thoubal', 'Bishnupur'], dic: 'Manipur DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-TR', name: 'Tripura', economicProfile: 'Agriculture (rubber, tea), natural gas, handicrafts. Agartala emerging as trade gateway.', majorCities: ['Agartala'], tier2Cities: ['Dharmanagar', 'Udaipur'], dic: 'Tripura DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-ML', name: 'Meghalaya', economicProfile: 'Mining, agriculture, tourism. Shillong is Scotland of the East.', majorCities: ['Shillong'], tier2Cities: ['Tura', 'Nongstoin'], dic: 'Meghalaya DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-NL', name: 'Nagaland', economicProfile: 'Agriculture, handicrafts, tourism (Hornbill Festival). Kohima is cultural hub.', majorCities: ['Kohima', 'Dimapur'], tier2Cities: ['Mokokchung'], dic: 'Nagaland DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-AR', name: 'Arunachal Pradesh', economicProfile: 'Hydropower, tourism, agriculture. Itanagar is emerging border economy hub.', majorCities: ['Itanagar'], tier2Cities: ['Naharlagun', 'Pasighat'], dic: 'Arunachal DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-MZ', name: 'Mizoram', economicProfile: 'Agriculture, bamboo industry, handicrafts. Aizawl is trade hub.', majorCities: ['Aizawl'], tier2Cities: ['Lunglei'], dic: 'Mizoram DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  { code: 'IN-SK', name: 'Sikkim', economicProfile: 'Tourism, organic farming, hydropower. First fully organic state in India.', majorCities: ['Gangtok'], tier2Cities: ['Namchi', 'Gyalshing'], dic: 'Sikkim DIC', gstThresholdNote: 'GST registration required above ₹10L turnover (NE special category)' },
  // Union Territories
  { code: 'IN-JK', name: 'Jammu & Kashmir', economicProfile: 'Tourism, handicrafts (pashmina, carpets), horticulture (apples, saffron). Emerging IT sector in Jammu.', majorCities: ['Srinagar', 'Jammu'], tier2Cities: ['Anantnag', 'Baramulla', 'Kathua'], dic: 'J&K DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-LA', name: 'Ladakh', economicProfile: 'Tourism (adventure, culture), renewable energy, border trade. Leh is gateway to high-altitude Himalayan region.', majorCities: ['Leh', 'Kargil'], tier2Cities: [], dic: 'Ladakh DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-CH', name: 'Chandigarh', economicProfile: 'Administrative, education, IT, trade. Planned city serving as capital of Punjab and Haryana.', majorCities: ['Chandigarh'], tier2Cities: [], dic: 'Chandigarh DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-PY', name: 'Puducherry', economicProfile: 'Tourism, IT, manufacturing, fisheries. French colonial heritage drives tourism.', majorCities: ['Puducherry'], tier2Cities: ['Karaikal', 'Mahe'], dic: 'Puducherry DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-AN', name: 'Andaman & Nicobar Islands', economicProfile: 'Tourism, fisheries, coconut. Port Blair is gateway to pristine island ecosystem.', majorCities: ['Port Blair'], tier2Cities: [], dic: 'A&N DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-LD', name: 'Lakshadweep', economicProfile: 'Tourism, coconut, fisheries. Emerging eco-tourism destination.', majorCities: ['Kavaratti'], tier2Cities: [], dic: 'Lakshadweep DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
  { code: 'IN-DN', name: 'Dadra & Nagar Haveli and Daman & Diu', economicProfile: 'Industrial hub near Gujarat; plastics, chemicals, textiles.', majorCities: ['Silvassa', 'Daman', 'Diu'], tier2Cities: [], dic: 'DNH DIC', gstThresholdNote: 'GST registration required above ₹20L turnover' },
];

const NIC_INDUSTRY_MAP = {
  'Technology': { nic: '62', nicDesc: 'Computer programming, consultancy and related activities', subSectors: ['Software development', 'IT consulting', 'Mobile app development', 'Cloud services', 'Cybersecurity'] },
  'Food & Beverage': { nic: '10', nicDesc: 'Manufacture of food products', subSectors: ['Cloud kitchen', 'Food processing', 'Packaged foods', 'Beverages', 'Catering'] },
  'Retail': { nic: '47', nicDesc: 'Retail trade, except of motor vehicles and motorcycles', subSectors: ['Grocery', 'Apparel', 'Electronics', 'D2C brand', 'E-commerce'] },
  'Healthcare': { nic: '86', nicDesc: 'Human health activities', subSectors: ['Clinic', 'Diagnostic centre', 'Pharmacy', 'Telemedicine', 'Health tech'] },
  'Education': { nic: '85', nicDesc: 'Education', subSectors: ['Coaching centre', 'EdTech', 'Vocational training', 'Preschool', 'Online tutoring'] },
  'Manufacturing': { nic: '25', nicDesc: 'Manufacture of fabricated metal products', subSectors: ['Small-scale manufacturing', 'Auto parts', 'Plastic goods', 'Garments', 'Furniture'] },
  'Real Estate': { nic: '68', nicDesc: 'Real estate activities', subSectors: ['Property broking', 'Rental management', 'Co-working', 'Interior design', 'PropTech'] },
  'Finance': { nic: '64', nicDesc: 'Financial service activities, except insurance and pension funding', subSectors: ['Microfinance', 'Accounting services', 'Tax consulting', 'Fintech', 'Insurance agency'] },
  'Tourism & Hospitality': { nic: '55', nicDesc: 'Accommodation', subSectors: ['Hotel/guesthouse', 'Travel agency', 'Home stays', 'Event management', 'Restaurant'] },
  'Agriculture': { nic: '01', nicDesc: 'Crop and animal production', subSectors: ['Organic farming', 'Agri-processing', 'Cold chain', 'Farm equipment rental', 'AgriTech'] },
  'Logistics': { nic: '49', nicDesc: 'Land transport and transport via pipelines', subSectors: ['Last-mile delivery', 'Warehousing', 'E-commerce logistics', 'Cold chain', 'Fleet management'] },
  'Beauty & Wellness': { nic: '96', nicDesc: 'Other personal service activities', subSectors: ['Salon', 'Spa & wellness', 'Fitness centre', 'Beauty products', 'Yoga studio'] },
  'Creative & Media': { nic: '90', nicDesc: 'Creative, arts and entertainment activities', subSectors: ['Content creation', 'Digital marketing', 'Photography', 'Event production', 'Gaming'] },
  'Construction': { nic: '41', nicDesc: 'Construction of buildings', subSectors: ['Civil contractor', 'Interior fit-out', 'Green building', 'Construction materials', 'Architecture firm'] },
  'Energy': { nic: '35', nicDesc: 'Electricity, gas, steam and air conditioning supply', subSectors: ['Solar installation', 'EV charging', 'Energy audit', 'Biogas', 'Energy efficiency'] },
};

const GOVT_SCHEMES = [
  { name: 'MUDRA Shishu', description: 'Loans up to ₹50,000 for micro businesses and new startups', eligibility: 'Non-corporate, non-farm micro/small enterprises', maxLoan: 50000, url: 'mudra.org.in' },
  { name: 'MUDRA Kishore', description: 'Loans from ₹50,001 to ₹5,00,000 for growing businesses', eligibility: 'Non-corporate, non-farm micro/small enterprises', maxLoan: 500000, url: 'mudra.org.in' },
  { name: 'MUDRA Tarun', description: 'Loans from ₹5,00,001 to ₹10,00,000 for established businesses', eligibility: 'Non-corporate, non-farm micro/small enterprises', maxLoan: 1000000, url: 'mudra.org.in' },
  { name: 'PMFME', description: 'PM Formalisation of Micro Food Enterprises — 35% credit-linked subsidy up to ₹10L for food processing units', eligibility: 'Existing micro food processing enterprises', maxLoan: 1000000, url: 'pmfme.mofpi.gov.in' },
  { name: 'PMEGP', description: 'PM Employment Generation Programme — 15–35% subsidy on project cost up to ₹25L (manufacturing) / ₹10L (services)', eligibility: 'Individuals 18+, SHGs, institutions', maxLoan: 2500000, url: 'kviconline.gov.in/pmegpeportal' },
  { name: 'Stand-Up India', description: 'Loans from ₹10L to ₹1Cr for SC/ST and women entrepreneurs for greenfield enterprises', eligibility: 'SC/ST or women borrowers, greenfield project', maxLoan: 10000000, url: 'standupmitra.in' },
  { name: 'CLCSS', description: 'Credit Linked Capital Subsidy Scheme — 15% upfront capital subsidy for technology upgradation', eligibility: 'Small-scale industries for technology upgrade', maxLoan: 1500000, url: 'dcmsme.gov.in' },
  { name: 'Startup India', description: 'Tax exemptions, fast-track IP registration, easier compliance for DPIIT-recognised startups', eligibility: 'Startups registered with DPIIT', maxLoan: null, url: 'startupindia.gov.in' },
  { name: 'GeM Portal', description: 'Government e-Marketplace — sell products/services directly to government departments', eligibility: 'Any registered business with Udyam/GST', maxLoan: null, url: 'gem.gov.in' },
];

function detectCityTier(cityName) {
  const tier1 = ['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad'];
  const tier2 = ['Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Pimpri', 'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubballi', 'Tiruchirappalli', 'Bareilly', 'Mysuru', 'Aligarh', 'Gurugram', 'Noida'];
  const name = cityName?.trim() || '';
  if (tier1.some(c => name.toLowerCase().includes(c.toLowerCase()))) return 1;
  if (tier2.some(c => name.toLowerCase().includes(c.toLowerCase()))) return 2;
  return 3;
}

function getIndiaStateByCode(code) {
  return INDIA_STATES.find(s => s.code === code);
}

function getRelevantSchemes(investmentINR) {
  return GOVT_SCHEMES.filter(s => !s.maxLoan || s.maxLoan >= investmentINR * 0.1).slice(0, 4);
}

module.exports = { INDIA_STATES, NIC_INDUSTRY_MAP, GOVT_SCHEMES, detectCityTier, getIndiaStateByCode, getRelevantSchemes };
